### ISSUE TITLE
Assistant to the Branch manager occasionally failing due to rate limit

### ISSUE THREAD

**Issue by devversion** [angular/dev-infra#961]
https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451

```
Run angular/dev-infra/github-actions/branch-manager@96fdaaa056f1cfa7ffbc[4](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:5)c69b7e9007279f76c94
Evaluating pull requests as a result of a push to 'refs/heads/main'
Triggering 190 prs to be evaluated
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48[5](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:6)83"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48581"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48580"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48579"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48578"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48577"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"4857[6](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:7)"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"485[7](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:8)4"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"4[8](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:9)56[9](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:10)"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48567"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48564"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48560"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48559"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48558"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48556"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48553"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48552"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48551"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48549"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48548"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48546"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48540"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48535"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48533"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48531"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48530"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48529"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48527"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48526"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48525"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48520"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48518"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48512"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48511"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48508"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48507"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48502"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48500"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48497"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48489"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48484"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48483"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48482"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48481"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48480"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48478"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48476"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48475"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48470"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48465"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48463"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48462"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48460"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48443"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48438"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48437"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48433"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48427"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48423"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48412"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48408"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48407"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48374"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48354"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48341"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48340"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48332"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48321"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48309"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48298"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48273"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48268"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48253"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48248"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48247"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48241"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48240"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48209"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48183"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48178"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48[10](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:11)6"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48103"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48100"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48080"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48072"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48071"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48070"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48069"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48065"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48048"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48042"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48039"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48037"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48025"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48023"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"480[11](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:12)"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48007"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48004"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"48000"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47999"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47998"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47982"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47972"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47971"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47966"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47965"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47944"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47937"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47936"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47934"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47924"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47907"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47906"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47850"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47838"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47837"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47835"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47833"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47807"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47801"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47778"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47773"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47684"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47634"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47614"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47582"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47550"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47543"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47485"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47461"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47447"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47419"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47404"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47401"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47368"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47341"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47332"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47326"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47261"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47233"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47218"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47214"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47096"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"47062"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46994"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46979"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46952"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46951"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46887"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46814"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46699"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46657"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46648"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46470"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46462"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46061"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46031"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"46028"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45945"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45824"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45807"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45793"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45696"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45660"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45552"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45516"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45447"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45383"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45273"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45230"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45211"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45142"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45[12](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:13)9"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"45023"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"44909"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"44499"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"44363"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"44328"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"44196"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"44194"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"43846"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"43744"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"43604"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"42112"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"40611"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"38916"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"38263"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"34862"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"29746"}
Requesting workflow run for: {"repo":"angular","owner":"angular","pr":"23784"}
RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at file:///home/runner/work/_actions/angular/dev-infra/96fdaaa056f1cfa7ffbc4c69b7e9007279f76c94/github-actions/branch-manager/main.js:14274:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 184)
    at async run (file:///home/runner/work/_actions/angular/dev-infra/96fdaaa056f1cfa7ffbc4c69b7e9007279f76c94/github-actions/branch-manager/main.js:23527:5)
    at async file:///home/runner/work/_actions/angular/dev-infra/96fdaaa056f1cfa7ffbc4c69b7e9007279f76c94/github-actions/branch-manager/main.js:23570:3 {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/angular/dev-infra/actions/workflows/branch-manager.yml/dispatches',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com objects-origin.githubusercontent.com secured-user-images.githubusercontent.com/ opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/",
      'content-type': 'application/json; charset=utf-8',
      date: 'Fri, 23 Dec 2022 14:17:04 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      'retry-after': '60',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '40C8:2D5E:538A380:AB451F2:63A5B85F',
      'x-xss-protection': '0'
    },
    data: {
      documentation_url: 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits',
      message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/angular/dev-infra/actions/workflows/branch-manager.yml/dispatches',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.4 octokit-core.js/4.0.5 Node.js/16.[13](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:14).0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"ref":"main","inputs":{"repo":"angular","owner":"angular","pr":"[40](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:41)[61](https://github.com/angular/angular/actions/runs/3766259367/jobs/6402572451#step:3:62)1"}}',
    request: { hook: [Function: bound bound register] }
  }
}
```

**Comment by alan-agius4** [comment]
Based on https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits one way to deal with this is to avoid concurrent requests.
